#!/usr/bin/python

# Generates sim/core/base_stats_levels_auto_gen.go: base attributes, health and mana for
# every race/class at levels 1-60, and the level curve of crit per agility and intellect.
#
# The attribute rows and base health come from the 1.12 world database (player_levelstats
# and player_classlevelstats, exported to CSV from the cmangos classic-db dump). Base mana
# and the crit curves come from the client's gtOCTBaseMPByClass, gtChanceToMeleeCrit and
# gtChanceToSpellCrit tables.
#
#   python3 tools/gen_level_base_stats.py

import csv

DIR = "assets/db_inputs/basestats/"
OUT = "sim/core/base_stats_levels_auto_gen.go"

RACES = {1: "Human", 2: "Orc", 3: "Dwarf", 4: "NightElf", 5: "Undead", 6: "Tauren", 7: "Gnome", 8: "Troll"}
CLASSES = {1: "Warrior", 2: "Paladin", 3: "Hunter", 4: "Rogue", 5: "Priest", 7: "Shaman", 8: "Mage", 9: "Warlock", 11: "Druid"}
# Column of each class in the gt tables.
GT_COLUMNS = {"Warrior": 1, "Paladin": 2, "Hunter": 3, "Rogue": 4, "Priest": 5, "Shaman": 7, "Mage": 8, "Warlock": 9, "Druid": 11}


def read_gt(name):
    rows = {}
    with open(DIR + name) as f:
        for line in f.read().splitlines()[1:]:
            parts = line.split("\t")
            if len(parts) < 12:
                continue
            rows[int(parts[0])] = [float(x) for x in parts[1:12]]
    return rows


levelstats = {}
with open(DIR + "player_levelstats.csv") as f:
    for r in csv.DictReader(f):
        levelstats.setdefault((int(r["race"]), int(r["class"])), {})[int(r["level"])] = (
            int(r["str"]), int(r["agi"]), int(r["sta"]), int(r["int"]), int(r["spi"]))

# Base attributes the Forever beta showed for a naked character with no talents (the Lua
# UnitStat values, 2026-10-07). Forever changed both the starting stats and the growth per
# level, so these rows replace the 1.12 ones. The other levels and races stay on 1.12 until
# we see them on the beta.
FOREVER_ATTRIBUTES = {
    (2, 7): {  # Orc shaman
        1: (24, 17, 22, 20, 22),
        30: (51, 30, 51, 46, 53),
    },
}
for (race, cls), levels in FOREVER_ATTRIBUTES.items():
    levelstats[(race, cls)].update(levels)

melee_crit = read_gt("chancetomeleecrit.txt")
spell_crit = read_gt("chancetospellcrit.txt")
base_mana = read_gt("octbasempbyclass.txt")

# We take base mana from the client's table rather than cmangos. The cmangos table has wrong
# rows, for example 718 for a level 30 shaman where the client and the Forever beta have 665.
classstats = {}
with open(DIR + "player_classlevelstats.csv") as f:
    for r in csv.DictReader(f):
        cls, level = int(r["class"]), int(r["level"])
        mana = int(r["basemana"])
        if cls in CLASSES and level <= 60:
            mana = round(base_mana[level][GT_COLUMNS[CLASSES[cls]] - 1])
        classstats.setdefault(cls, {})[level] = (int(r["basehp"]), mana)

out = []
out.append("package core\n")
out.append("// **************************************")
out.append("// AUTO GENERATED BY GEN_LEVEL_BASE_STATS.PY")
out.append("// **************************************\n")
out.append('import "github.com/wowsims/classic/sim/core/proto"\n')

out.append("// Strength, Agility, Stamina, Intellect and Spirit at each level, index 0 is level 1.")
out.append("var levelAttributes = map[RaceClass][60][5]int16{")
for (race, cls), levels in sorted(levelstats.items()):
    if race not in RACES or cls not in CLASSES:
        continue
    out.append(f"\t{{proto.Race_Race{RACES[race]}, proto.Class_Class{CLASSES[cls]}}}: {{")
    for start in range(1, 61, 10):
        row = ", ".join("{%d, %d, %d, %d, %d}" % levels[l] for l in range(start, start + 10))
        out.append(f"\t\t{row},")
    out.append("\t},")
out.append("}\n")

out.append("// Base health and mana at each level, index 0 is level 1.")
out.append("var levelHealthMana = map[proto.Class][60][2]int16{")
for cls, levels in sorted(classstats.items()):
    if cls not in CLASSES:
        continue
    out.append(f"\tproto.Class_Class{CLASSES[cls]}: {{")
    for start in range(1, 61, 10):
        row = ", ".join("{%d, %d}" % levels[l] for l in range(start, start + 10))
        out.append(f"\t\t{row},")
    out.append("\t},")
out.append("}\n")


def curve(name, table, comment):
    out.append(comment)
    out.append(f"var {name} = map[proto.Class][60]float64{{")
    for cls, col in GT_COLUMNS.items():
        out.append(f"\tproto.Class_Class{cls}: {{")
        for start in range(1, 61, 10):
            out.append("\t\t" + ", ".join("%.6f" % table[l][col - 1] for l in range(start, start + 10)) + ",")
        out.append("\t},")
    out.append("}\n")


curve("meleeCritPerAgiCurve", melee_crit, "// Melee crit chance per point of Agility at each level (gtChanceToMeleeCrit), index 0 is level 1.")
curve("spellCritPerIntCurve", spell_crit, "// Spell crit chance per point of Intellect at each level (gtChanceToSpellCrit), index 0 is level 1.")

with open(OUT, "w") as f:
    f.write("\n".join(out))
